### ISSUE TITLE
source maps seem to be corrupted when using stealjs

### ISSUE THREAD

**Issue by wrldtrvllr** [stealjs/steal#726]
Hi guys, I need your help.

I've successfully managed to create an angular2 app in Typescript (to be more precise, the heroes-tutorial) and load the application with stealjs and the npm plugin. Altogether, this makes using angular2 very easy to setup and use.
Unfortunately, the source maps which map the Typescript code to the JavaScript code seem to be corrupt when using steal. In Chrome developer tools, I can see the Typescript files which have been restored from the JavaScript and the corresponding source maps. However, if i want to set a breakpoint in one of the *.ts files, the breakpoint is actually set in a completely different line of the file. Of course, the breakpoint is not hit as well.

I compared the initial systemjs configuration with the stealjs configuration and with systemjs everything works as expected. Therefore I come to the conclusion that it's probably stealjs which breaks something here.

To help you debug the issue, I've setup a github repository with my configuration (please refer to https://github.com/wrldtrvllr/stealjsbug). Any help or advice will be highly appreciated. If we can fix this, I think we will have a neat way to bootstrap angular2 apps without all the systemjs configuration overhead.

Thanks in advance!

**Comment by matthewp** [comment]
Thanks, i'll take a look.

**Comment by matthewp** [comment]
Can you make a branch of this project that uses systemjs so I can compare our implementation against theirs?

**Comment by wrldtrvllr** [comment]
There exists a second branch "systemjs" besides "master" now.

**Comment by matthewp** [comment]
Thanks!

**Comment by wrldtrvllr** [comment]
I've made some progress on this issue. Sourcemaps break when I let typescript create CommonJS modules ("module": "commonjs" in tsconfig.json). If I set module output to "system", sourcemaps work as expected. However, with system modules, steal crashes with a "core_1.Injectable is not a function" error message. This seems to be an issue with steal and/or angular2. I narrowed the error down to the following part in function `linkDeclarativeModule` in steal.js:
```
if (depEntry.module.exports && depEntry.module.exports.__esModule)
    depExports = depEntry.module.exports;
else
    depExports = { 'default': depEntry.module.exports, '__useDefault': true };
```
The angular modules don't have the __esModule property set, so the exports are wrapped in a `default` property by steal. However, the generated code expects the `Injectable` function to be present directly in `depExports` and not in `depExports.default`. If i comment out the else part and always assign the exports to `depExports`, the app works.
Actually, I'm not quite sure why you'd need the wrapping in a default property.

Anyways, it's not a solution for the initial bugreport, as commonjs modules seem to break the sourcemaps with steal. But I hope it helps you figuring out the problem.

**Comment by matthewp** [comment]
Thanks!  Would you be willing to try out the prerelease?  If you install `npm install steal@pre --save` you'll get the latest. The line you refer to above has been changed. Not sure if it will help your issue or not.  If not, I'll investigate further. Thanks again!

**Comment by wrldtrvllr** [comment]
Tried the prerelease and the "core_1.Injectable is not a function" error is gone. However, now both system and commonjs module format screw up sourcemaps. Only exception is when the transpilation target of typescript is ES6 instead of ES5, but I don't think this is a sensible workaround. I'm not quite sure if it's an issue of typescript as well, but systemjs is working as expected. The git repo is up-to-date. If you need further help, let me know!

**Comment by matthewp** [comment]
Thanks!  I'll try and take a look soon.  Working on getting a 1.0 release out, then will have time to look at bugs like this.

**Comment by matthewp** [comment]
Hey @wrldtrvllr, sorry for taking so long to get back to you. I cloned your app but wasn't able to load it. Not sure if something else in Angular has broken it or what is going on. Either way, to debug these types of issues its important to have a minimal example, the least amount of code needed to reproduce the problem.

In your case the problem was in regards to TypeScript, so I would think it would be possible to create a project with TypeScript that gets compiled and then loaded with Steal. And if the problem is there, we should be able to see it. No Angular or any other dependencies needed. Going to close for now, but if you can produce a smaller example I'd be happy to take a look.
