### ISSUE TITLE
Less files don’t work in 1.0.0-rc.1

### ISSUE THREAD

**Issue by chasenlehara** [stealjs/steal#830]
Steps to reproduce:
1. Create a new project folder.
2. Run `donejs add plugin` in your new folder and fill out the prompts with the defaults.
3. Change `package.json` to use `steal@1.0.0-rc.1` and `steal-tools@1.0.0-rc.0`
4. Run `npm install`
5. Run `donejs add component test` and fill out the prompts with the defaults.
6. Run `donejs develop`
7. Go to `http://localhost:8080/src/test/test.html`

Expected results: component tests load without issues

Actual results: error in the console: `TypeError: Error loading "steal-1-rc-1-less-bug@0.0.0#test/test.less!$less" from "steal-1-rc-1-less-bug@0.0.0#test/test_test" at http://localhost:8080/src/test/test_test.js
liveReload.isReloading is not a function`

Additional notes:
- This can be worked around by removing `live-reload` from `system.configDependencies` in the `package.json`
- This seems like a regression from 0.16
- I’ve created a repo that has the first five steps already done: https://github.com/chasenlehara/steal-1-rc1-less-bug

**Comment by pYr0x** [comment]
yeah, it is a bug
this line: https://github.com/stealjs/steal/blob/1c5da6485918385774d0c92c99229bcdd744aebc/ext/less.js#L15 cause the error. it seems that `get()` is not getting the module. live-reload is in the `modulepath`. but it seems that it is an empty module. dont know why

**Comment by matthewp** [comment]
This is the root bug, I'll fix it tomorrow: https://github.com/stealjs/steal-less/issues/28

**Comment by matthewp** [comment]
Fixed in steal 1.0.0-rc.2
